info:
  version: 1.0.0
  date: 2025-01-23
  stage: development
  autor: Daniel Arcos
  email: darcos@banred.fin.ec
  description: JWE BR
server:
  port: 8443
  servlet:
    context-path: /api
  compression:
    enabled: true
  error:
    include-message: never
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
  address: 0.0.0.0
  undertow:
    threads:
      io: 10
      worker: 256
    allow-encoded-slash: false
    always-set-keep-alive: true
    decode-url: true
    eager-filter-init: true
    max-cookies: 200
    max-headers: 200
    max-http-post-size: 10MB
    preserve-path-on-forward: false
    url-charset: UTF-8

spring:
  main:
    log-startup-info: true
    banner-mode: console
  thymeleaf:
    enabled: false
  jackson:
    default-property-inclusion: non-null
    serialization:
      write-date-keys-as-timestamps: false
    time-zone: GMT-5
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: microservicioAPITest
  datasource:
    url: jdbc:mysql://localhost:3306/pruebabr
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #UPDATE